import type { Metadata } from "next";
import { Carlito, Fira_Code } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const carlito = Carlito({
  variable: "--font-carlito",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${carlito.variable} ${firaCode.variable} ${carlito.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
